# Introduction to Dataframes

In [2]:
import pandas as pd

df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], columns=['A', 'B', 'C'], index=['x', 'y', 'z', 'w'])

In [3]:
df.head()
df.tail()

    A   B   C
x   1   2   3
y   4   5   6
z   7   8   9
w  10  11  12

In [4]:
df.columns
df.index

Index(['x', 'y', 'z', 'w'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to w
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [6]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [7]:
df.size

12

In [8]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [9]:
df['A'].unique()

array([ 1,  4,  7, 10])

# Loading in Dataframes from Files

In [10]:
coffee = pd.read_csv('https://raw.githubusercontent.com/jethzgg/Data-ML/refs/heads/main/Pandas/coffee.csv')
#read_parquet
#read_excel

In [11]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [12]:
bios = pd.read_csv('https://raw.githubusercontent.com/jethzgg/Data-ML/refs/heads/main/Pandas/bios.csv')

In [13]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [14]:
#bios.to_excel()

# Accessing Data with Pandas

In [15]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [16]:
coffee.sample(10, random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [17]:
# Filter
# loc[# Name of Row, # Name of Col]
coffee.loc[0, 'Day']

'Monday'

In [18]:
coffee.loc[[0, 1, 2], ['Day', 'Coffee Type']]

       Day Coffee Type
0   Monday    Espresso
1   Monday       Latte
2  Tuesday    Espresso

In [19]:
#coffee.loc[1:3, 'Units Sold'] = 10

In [20]:
coffee.loc[:, ['Day', 'Units Sold']]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [21]:
# iloc : index location
coffee.iloc[0:5,[0,2]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [22]:
coffee.at[0, 'Day']

'Monday'

In [23]:
coffee.iat[0, 0]

'Monday'

In [24]:
coffee['Day']

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [25]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [26]:
coffee.sort_values(['Units Sold', 'Coffee Type'], ascending=[0,1])
# First sort by Units Sold in descending order, then by Coffee Type in ascending order.

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [27]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print()
    print(row['Day'], row['Coffee Type'], row['Units Sold'])
    print()

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

Monday Espresso 25

1
Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object

Monday Latte 15

2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object

Tuesday Espresso 30

3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object

Tuesday Latte 20

4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object

Wednesday Espresso 35

5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object

Wednesday Latte 25

6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object

Thursday Espresso 40

7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object

Thursday Latte 30

8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object

Friday Espresso 45

9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object

Friday Latte 35

10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object

Saturday Espresso 45

11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object

Saturday Latte 35

12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object

Sunday Espresso 45

13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

Sunday Latte 35

# Filtering Dataframes

In [28]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [29]:
bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [30]:
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')][['name', 'height_cm', 'born_country']]

                    name  height_cm born_country
5781      Tommy Burleson      223.0          USA
6722    Shaquille O'Neal      216.0          USA
6937      David Robinson      216.0          USA
123850    Tyson Chandler      216.0          USA

In [31]:
bios[bios['name'].str.contains('keith|patrick', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [32]:
bios[bios['born_country'].isin(['USA', 'FRA', 'GBR']) & bios['name'].str.startswith('Keith')][['name', 'born_country']]

                      name born_country
3505         Keith Wallace          GBR
12053         Keith Hervey          GBR
14577       Keith Harrison          GBR
16166       Keith Reynolds          GBR
18734       Keith Sinclair          GBR
29897        Keith Langley          GBR
34011         Keith Remfry          GBR
46885         Keith Collin          GBR
50929         Keith Carter          USA
51185        Keith Russell          USA
52913       Keith Erickson          USA
55317         Keith Boxell          GBR
57818         Keith Peache          GBR
61748        Keith Grogono          GBR
62620          Keith Musto          GBR
62678         Keith Notary          USA
68324          Keith Angus          GBR
68472         Keith Cullen          GBR
68997          Keith Stock          GBR
77550        Keith Brantly          USA
84097   Keith Christiansen          USA
94646          Keith Meyer          USA
95267         Keith Oliver          GBR
96452   Keith Schellenberg          GBR
97499        Keith Tkachuk          USA
98068        Keith Wegeman          USA
99921         Keith Carney          USA
115973     Keith Sanderson          USA

In [33]:
bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

# Adding / Removing Columns

In [34]:
coffee['price'] = 4.99

In [35]:
import numpy as np

coffee['new price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)

In [36]:
coffee.drop(columns=['price'], inplace=True)
# inplace=True means that the original DataFrame will be modified and the 'price' column will be removed from it. If inplace=False (or not specified), a new DataFrame will be returned with the 'price' column removed, and the original DataFrame will remain unchanged.

In [37]:
coffee = coffee[['Day', 'Coffee Type', 'Units Sold', 'new price']]

In [38]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new price']

In [39]:
coffee.rename(columns={'new price': 'price'}, inplace=True)

In [40]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [41]:
bios_new = bios.copy()

In [42]:
bios_new['first_name'] = bios_new['name'].str.split(" ").str[0]

In [43]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [44]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

In [45]:
def categorize_athlete(row):
    if row['height_cm'] > 200:
        return 'Tall'
    elif row['height_cm'] < 160:
        return 'Short'
    else:
        return 'Average'

bios['Category'] = bios.apply(categorize_athlete, axis=1)

In [46]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Average

# Merge / Concatenating Dataframes

In [47]:
nocs = pd.read_csv('https://raw.githubusercontent.com/jethzgg/Data-ML/refs/heads/main/Pandas/noc_regions.csv')

In [48]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [49]:
bios_new.rename(columns={'region': 'born_country_full'}, inplace=True)

In [50]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,Category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Average,GBR,UK,NaN

In [51]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name',  'NOC_x', 'born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [52]:
usa = bios_new[bios_new['born_country'] == 'USA'].copy()
gbr = bios_new[bios_new['born_country'] == 'GBR'].copy()

In [53]:
new_df = pd.concat([usa, gbr], ignore_index=True)

In [54]:
results = pd.read_csv('https://raw.githubusercontent.com/jethzgg/Data-ML/refs/heads/main/Pandas/results.csv')

In [55]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [56]:
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [57]:
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,...,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN,Average
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,...,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN,Average
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,...,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,Average
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,...,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,Average
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,...,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN,Average

# Handling Null Values

In [58]:
coffee.loc[[2,3], 'Units Sold'] = np.nan
coffee.loc[[0,1], 'Units Sold'] = 15
# coffee.dropna(subset=['Units Sold'], inplace=True)

In [59]:
coffee[coffee['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  revenue
2  Tuesday    Espresso         NaN   3.99    119.7
3  Tuesday       Latte         NaN   5.99    119.8

In [60]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [61]:
coffee['Units Sold'].interpolate()

0     15.000000
1     15.000000
2     21.666667
3     28.333333
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [62]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

# Aggregating Data

In [63]:
bios[bios['born_country'] == 'USA']['born_region'].value_counts()
# value_counts() returns a Series containing counts of unique values. The resulting object will be in descending order so that the first element is the most frequently-occurring element.

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [64]:
coffee.groupby('Coffee Type')['Units Sold'].sum()

Coffee Type
Espresso    246.666667
Latte       203.333333
Name: Units Sold, dtype: float64

In [65]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})
# agg means aggregate. It allows you to apply multiple aggregation functions to different columns of a DataFrame. In this case, we are calculating the sum of 'Units Sold' and the mean of 'price' for each 'Coffee Type'.

                       Units Sold  price
Coffee Type Day
Espresso    Friday      45.000000   3.99
            Monday      15.000000   3.99
            Saturday    45.000000   3.99
            Sunday      45.000000   3.99
            Thursday    40.000000   3.99
            Tuesday     21.666667   3.99
            Wednesday   35.000000   3.99
Latte       Friday      35.000000   5.99
            Monday      15.000000   5.99
            Saturday    35.000000   5.99
            Sunday      35.000000   5.99
            Thursday    30.000000   5.99
            Tuesday     28.333333   5.99
            Wednesday   25.000000   5.99

In [66]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

In [67]:
pivot.sum()
# axis = 0: row
# axis = 1: column

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [68]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

In [69]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios['born_year'] = bios['born_date'].dt.year
bios['born_month'] = bios['born_date'].dt.month
bios.groupby([bios['born_year'], bios['born_month']])['name'].count().reset_index().sort_values('name', ascending=False)

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

# Advanced Functionality

In [70]:
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [71]:
coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100

In [72]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000

In [73]:
bios['height_rank'] = bios['height_cm'].rank()

In [77]:
bios.sort_values('height_rank', ascending=True)[['name', 'height_rank']]

                         name  height_rank
4515            Lyton Mphande          1.5
28619         Rosario Briones          1.5
4516            Helman Palije          3.0
4664         Salvador Miranda          4.5
4517           Boston Simbeye          4.5
...                       ...          ...
145490            Sin Ye-Chan          NaN
145491          Matthew Wepke          NaN
145492  Carlos García-Ordóñez          NaN
145493     Landysh Falyakhova          NaN
145499          Bill Phillips          NaN

[145500 rows x 2 columns]

In [80]:
coffee['cumulative_revenue'] = coffee['revenue'].cumsum()

In [83]:
latte = coffee[coffee['Coffee Type'] == 'Latte'].copy()
latte['3 days'] = latte['Units Sold'].rolling(3).sum()

In [84]:
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3 days
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5,68.333333
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8,83.333333
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0,90.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4,105.000000

# New Functionality in Pandas

In [85]:
results_numpy = pd.read_csv('https://raw.githubusercontent.com/jethzgg/Data-ML/refs/heads/main/Pandas/results.csv')

In [ ]:
results_arrow = pd.read_csv('https://raw.githubusercontent.com/jethzgg/Data-ML/refs/heads/main/Pandas/results.csv', engine='pyarrow', dtype_backend='pyarrow')
# pyarrow compared to numpy, pyarrow is faster and more memory efficient for large datasets. It also supports more data types and has better support for missing values. However, it may have some limitations in terms of functionality and compatibility with certain libraries.

In [87]:
results_numpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [88]:
results_arrow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB

In [89]:
results_numpy['as'].str.contains('Keith')

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Name: as, Length: 308408, dtype: bool

In [90]:
results_arrow['as'].str.contains('Keith')

0         False
1         False
2         False
3         False
4         False
          ...
308403    False
308404    False
308405    False
308406    False
308407    False
Name: as, Length: 308408, dtype: bool[pyarrow]