In [19]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)
def create_data():
    data = {
        "Age": np.random.randint(18, 70, size=20),
        "Salary": np.random.randint(30000, 120000, size=20),
        "Purchased": np.random.choice([0, 1], size=20),
        "Gender": np.random.choice(["Male", "Female"], size=20),
        "City": np.random.choice(["New York", "San Francisco", "Los Angeles"], size=20)
    }

    df = pd.DataFrame(data)
    return df

df = create_data()
df.head(10)

   Age  Salary  Purchased  Gender           City
0   56   92955          1  Female  San Francisco
1   69   94925          0  Female  San Francisco
2   46   97969          0    Male       New York
3   32   35311          0  Female    Los Angeles
4   60  113104          0    Male  San Francisco
5   25   83707          0  Female  San Francisco
6   38  115305          0    Male  San Francisco
7   56   58693          0  Female  San Francisco
8   36  101932          0    Male  San Francisco
9   40   55658          1    Male  San Francisco

# When you have missing value in data

In [16]:
# Introduce some missing values
df.loc[5, "Age"] = np.nan
df.loc[10, "Salary"] = np.nan
df.head(11)

     Age    Salary  Purchased  Gender           City  Age_missing
0   56.0   92955.0          1  Female  San Francisco            0
1   69.0   94925.0          0  Female  San Francisco            0
2   46.0   97969.0          0    Male       New York            0
3   32.0   35311.0          0  Female    Los Angeles            0
4   60.0  113104.0          0    Male  San Francisco            0
5    NaN   83707.0          0  Female  San Francisco            0
6   38.0  115305.0          0    Male  San Francisco            0
7   56.0   58693.0          0  Female  San Francisco            0
8   36.0  101932.0          0    Male  San Francisco            0
9   40.0   55658.0          1    Male  San Francisco            0
10  28.0       NaN          1  Female    Los Angeles            0

### Simple Imputation (mean, median, mode)
Pros: Fast and straight forward.

Cons: May introduce bias if missing data is not random.

In [9]:
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Salary"].fillna(df["Salary"].median(), inplace=True)
df.head(11)

          Age    Salary  Purchased  Gender           City
0   56.000000   92955.0          1  Female  San Francisco
1   69.000000   94925.0          0  Female  San Francisco
2   46.000000   97969.0          0    Male       New York
3   32.000000   35311.0          0  Female    Los Angeles
4   60.000000  113104.0          0    Male  San Francisco
5   42.105263   83707.0          0  Female  San Francisco
6   38.000000  115305.0          0    Male  San Francisco
7   56.000000   58693.0          0  Female  San Francisco
8   36.000000  101932.0          0    Male  San Francisco
9   40.000000   55658.0          1    Male  San Francisco
10  28.000000   92955.0          1  Female    Los Angeles

### Listwise Deletion
Pros: Simple.

Cons: Loosing data.

In [12]:
df_dropped = df.dropna()
df_dropped.head(11)

     Age    Salary  Purchased  Gender           City
0   56.0   92955.0          1  Female  San Francisco
1   69.0   94925.0          0  Female  San Francisco
2   46.0   97969.0          0    Male       New York
3   32.0   35311.0          0  Female    Los Angeles
4   60.0  113104.0          0    Male  San Francisco
6   38.0  115305.0          0    Male  San Francisco
7   56.0   58693.0          0  Female  San Francisco
8   36.0  101932.0          0    Male  San Francisco
9   40.0   55658.0          1    Male  San Francisco
11  28.0   48431.0          0    Male    Los Angeles
12  41.0   32747.0          1  Female  San Francisco

### Predictive Imputation - Search for MICE imputation as well
Pros: More accurate for complex patterns.

Cons: Computationally intensive, may add noise with high variance.

In [14]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
df[["Age", "Salary"]] = imputer.fit_transform(df[["Age", "Salary"]])
df.head(11)

          Age         Salary  Purchased  Gender           City
0   56.000000   92955.000000          1  Female  San Francisco
1   69.000000   94925.000000          0  Female  San Francisco
2   46.000000   97969.000000          0    Male       New York
3   32.000000   35311.000000          0  Female    Los Angeles
4   60.000000  113104.000000          0    Male  San Francisco
5   42.666667   83707.000000          0  Female  San Francisco
6   38.000000  115305.000000          0    Male  San Francisco
7   56.000000   58693.000000          0  Female  San Francisco
8   36.000000  101932.000000          0    Male  San Francisco
9   40.000000   55658.000000          1    Male  San Francisco
10  28.000000   49838.333333          1  Female    Los Angeles

### Add indicator for missingness
Pros: Allows model to learn from missingness.

Cons: Can invrease dimensionality and complexity.

In [17]:
df["Age_missing"] = df["Age"].isnull().astype(int)
df.head(11)

     Age    Salary  Purchased  Gender           City  Age_missing
0   56.0   92955.0          1  Female  San Francisco            0
1   69.0   94925.0          0  Female  San Francisco            0
2   46.0   97969.0          0    Male       New York            0
3   32.0   35311.0          0  Female    Los Angeles            0
4   60.0  113104.0          0    Male  San Francisco            0
5    NaN   83707.0          0  Female  San Francisco            1
6   38.0  115305.0          0    Male  San Francisco            0
7   56.0   58693.0          0  Female  San Francisco            0
8   36.0  101932.0          0    Male  San Francisco            0
9   40.0   55658.0          1    Male  San Francisco            0
10  28.0       NaN          1  Female    Los Angeles            0

# When you have Categorical Variables in data

### Label Encoding
Pros: Simple and space-efficient.

Cons: Implies ordinal relationship, which may mislead the model.

In [19]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["Gender"] = label_encoder.fit_transform(df["Gender"])
df.head()

   Age  Salary  Purchased  Gender           City
0   56   92955          1       0  San Francisco
1   69   94925          0       0  San Francisco
2   46   97969          0       1       New York
3   32   35311          0       0    Los Angeles
4   60  113104          0       1  San Francisco

### One-hot Encoding
Pros: Great for non-ordinal categories, maintain all category information.

Cons: Increases dimensionality, particularly with many unique values.

In [25]:
df = pd.get_dummies(df, columns=["City"], drop_first=True)
df.head()

   Age  Salary  Purchased  Gender  City_New York  City_San Francisco
0   56   92955          1  Female          False                True
1   69   94925          0  Female          False                True
2   46   97969          0    Male           True               False
3   32   35311          0  Female          False               False
4   60  113104          0    Male          False                True

### Ordinal Encoding
Pros: Effective for ordinal data, captures order.

Cons: Not suitable for non-ordinal data, as it implies ranking.

In [27]:
df["City"] = df["City"].map({"New York": 1, "San Francisco": 2, "Los Angeles": 3})
df.head()

   Age  Salary  Purchased  Gender  City
0   56   92955          1  Female     2
1   69   94925          0  Female     2
2   46   97969          0    Male     1
3   32   35311          0  Female     3
4   60  113104          0    Male     2

### Target Encoding
Pros: Useful for high-cardinality categorical variables.

Cons: Can cause data leakage if target encoding is not done properly.

In [30]:
mean_target = df.groupby("City")["Purchased"].mean()
df["City_target_encoded"] = df["City"].map(mean_target)
df.head()

   Age  Salary  Purchased  Gender           City  City_target_encoded
0   56   92955          1  Female  San Francisco             0.363636
1   69   94925          0  Female  San Francisco             0.363636
2   46   97969          0    Male       New York             0.500000
3   32   35311          0  Female    Los Angeles             0.600000
4   60  113104          0    Male  San Francisco             0.363636

#### When to use
- Use label encoding for ordinal categorical variables.
- Use one-hot encoding for nominal categorical variables with low cardinality.
- Use ordinal encoding for ordinal categorical variables.
- Use target encoding for high-cardinality categorical variables, but ensure to avoid data leakage by applying it only on training data and using cross-validation.

# When you need to scale your data

In [2]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

### Standardization (mean=0, variance=1)
Pros: Works well for normally distributed data, suitable for many models.

Cons: Sensitive to outliers.

In [33]:
scaler = StandardScaler()
df[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])
df.head()

        Age    Salary  Purchased  Gender           City
0  1.090687  0.328914          1  Female  San Francisco
1  2.051970  0.406302          0  Female  San Francisco
2  0.351238  0.525879          0    Male       New York
3 -0.683990 -1.935513          0  Female    Los Angeles
4  1.386466  1.120427          0    Male  San Francisco

### Normalization (range [0,1])
Pros: Keeps all data between 0 and 1, ideal for distance-based models.

Cons: Can distort data distribution, sensitive to outliers.

In [3]:
normalizer = MinMaxScaler()
df[["Age", "Salary"]] = normalizer.fit_transform(df[["Age", "Salary"]])
df.head()

    Age    Salary  Purchased  Gender           City
0  0.74  0.729281          1  Female  San Francisco
1  1.00  0.753143          0  Female  San Francisco
2  0.54  0.790014          0    Male       New York
3  0.26  0.031057          0  Female    Los Angeles
4  0.82  0.973340          0    Male  San Francisco

### Robust Scaling (median=0, IQR=1, robust to outliers)
Pros: More robust to outliers by using median and IQR.

Cons: Does not work as well for normal distributions.

In [5]:
robust_scaler = RobustScaler()
df[["Age", "Salary"]] = robust_scaler.fit_transform(df[["Age", "Salary"]])
df.head()

        Age    Salary  Purchased  Gender           City
0  0.681319 -0.028178          1  Female  San Francisco
1  1.252747  0.028178          0  Female  San Francisco
2  0.241758  0.115257          0    Male       New York
3 -0.373626 -1.677187          0  Female    Los Angeles
4  0.857143  0.548220          0    Male  San Francisco

#### When to use
- Use standardization for normally distributed data or when using models that assume normality and outliers are cleaned.
- Use normalization for distance-based models, when features have different scales or you need to transform it to 0 and 1 scale.
- Use robust scaling when data contains outliers and you want to minimize their impact on the scaling process.

# When you have outliers in data

### Outlier Detection and Treatment using IQR
Pros: Simple and effective for mild outliers.

Cons: May overly reduce variation if there are many extreme outliers.

In [ ]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
# 1.5 is a common multiplier for IQR to detect outliers
df["Salary"] = np.where(df["Salary"] > upper_bound, upper_bound, 
                        np.where(df["Salary"] < lower_bound, lower_bound, 
                                 df["Salary"]))
df.head()

   Age    Salary  Purchased  Gender           City
0   56   92955.0          1  Female  San Francisco
1   69   94925.0          0  Female  San Francisco
2   46   97969.0          0    Male       New York
3   32   35311.0          0  Female    Los Angeles
4   60  113104.0          0    Male  San Francisco

### Z-score method
Pros: Effective for normally distributed data.

Cons: Not suitable for non-normal distributions, may miss outliers in skewed distributions.

In [ ]:
from scipy import stats
df["Salary_zscore"] = stats.zscore(df["Salary"])
df["Salary"] = np.where(df["Salary_zscore"].abs() > 3, np.nan, df["Salary"])
# 3 is a common threshold
df.head()

   Age    Salary  Purchased  Gender           City  Salary_zscore
0   56   92955.0          1  Female  San Francisco       0.328914
1   69   94925.0          0  Female  San Francisco       0.406302
2   46   97969.0          0    Male       New York       0.525879
3   32   35311.0          0  Female    Los Angeles      -1.935513
4   60  113104.0          0    Male  San Francisco       1.120427

### Median replacement for outliers
Pros: Keep distribution shape intact, useful when capping is not feasible.

Cons: May distort data if outliers represent real phenomena, not errors.

In [16]:
df["Salary_zscore"] = stats.zscore(df["Salary"])
median_salary = df["Salary"].median()
df["Salary"] = np.where(df["Salary_zscore"].abs() > 3, median_salary, df["Salary"])
df.head()

   Age    Salary  Purchased  Gender           City  Salary_zscore
0   56   92955.0          1  Female  San Francisco       0.328914
1   69   94925.0          0  Female  San Francisco       0.406302
2   46   97969.0          0    Male       New York       0.525879
3   32   35311.0          0  Female    Los Angeles      -1.935513
4   60  113104.0          0    Male  San Francisco       1.120427

#### When to use
- Outlier detection and treatment using IQR is suitable for mild outliers.
- Z-score method is effective for normally distributed data.
- Median replacement for outliers is useful when capping is not feasible and you want to maintain the distribution shape intact.

# Feature engineering

### Creating a new feature based on Salary (Discretization)
Pros: Simplified continuous features; useful for non-linear models.

Cons: Can lose data granularity, potentially reducing model accuracy.

In [20]:
df["Income_Level"] = pd.cut(df["Salary"], bins=[0, 50000, 100000, 150000], labels=["Low", "Medium", "High"])
df.head(10)

   Age  Salary  Purchased  Gender           City Income_Level
0   56   92955          1  Female  San Francisco       Medium
1   69   94925          0  Female  San Francisco       Medium
2   46   97969          0    Male       New York       Medium
3   32   35311          0  Female    Los Angeles          Low
4   60  113104          0    Male  San Francisco         High
5   25   83707          0  Female  San Francisco       Medium
6   38  115305          0    Male  San Francisco         High
7   56   58693          0  Female  San Francisco       Medium
8   36  101932          0    Male  San Francisco         High
9   40   55658          1    Male  San Francisco       Medium

# Polynomial Features
Pros: Captures complex relationships between features, can improve model performance.

Cons: Increases dimensionality, can lead to overfitting if not regularized properly.

In [21]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=False)
poly_features = poly.fit_transform(df[["Age", "Salary"]])
df_poly = pd.DataFrame(poly_features, columns=poly.get_feature_names_out(["Age", "Salary"]))
df = pd.concat([df, df_poly], axis=1)
df.head()

,Age,Salary,Purchased,Gender,City,Income_Level,Age,Salary,Age^2,Age Salary,Salary^2
0,56,92955,1,Female,San Francisco,Medium,56.0,92955.0,3136.0,5205480.0,8.640632e+09
1,69,94925,0,Female,San Francisco,Medium,69.0,94925.0,4761.0,6549825.0,9.010756e+09
2,46,97969,0,Male,New York,Medium,46.0,97969.0,2116.0,4506574.0,9.597925e+09
3,32,35311,0,Female,Los Angeles,Low,32.0,35311.0,1024.0,1129952.0,1.246867e+09
4,60,113104,0,Male,San Francisco,High,60.0,113104.0,3600.0,6786240.0,1.279251e+10

#### When to use
- Use Discretization when you want to simplify continuous features and capture non-linear relationships.
- Use Polynomial Features when you want to capture complex relationships between features, but be cautious of overfitting and increased dimensionality.